(load "tractatus-core.lisp")
(load "tractatus-periphery.lisp")
(load "tractatus-worlds.lisp")
(load "tractatus-axes.lisp")

(in-package #:cl)

(defun expect (condition message)
  (unless condition
    (error "Test failed: ~A" message)))

(let ((world (tractatus-worlds::make-lex-welt "wikipu-ecosystem" "cocina")))
  (tractatus-axes::define-axis world :parte-comestible '(hoja raiz tallo))
  (tractatus-axes::define-axis world :rol '(alimento ingrediente mascota))
  (tractatus-axes::project-concept world 'lechuga :parte-comestible 'hoja)
  (tractatus-axes::project-concept world 'zanahoria :parte-comestible 'raiz)
  (tractatus-axes::project-concept world 'apio :parte-comestible 'tallo)
  (tractatus-axes::project-concept world 'lechuga :rol 'alimento)
  (tractatus-axes::project-concept world 'zanahoria :rol 'alimento)
  (tractatus-axes::project-concept world 'apio :rol 'ingrediente)
  (expect (string= (tractatus-axes::concept-axis-bitstring world 'lechuga :parte-comestible)
                   "100")
          "leaf vegetables should map to the first bit")
  (expect (string= (tractatus-axes::concept-signature world 'zanahoria
                                                      :axis-order '(:parte-comestible :rol))
                   "010100")
          "concept signature should concatenate contextual axis bits")
  (expect (string= (tractatus-axes::contextual-signature world 'lechuga '(:rol))
                   "000100")
          "context masks should isolate the active axis")
  (expect (equal (tractatus-axes::matching-concepts world 'lechuga '(:rol))
                 '(lechuga zanahoria))
          "matching within one active axis should group compatible concepts")
  (format t "Axes smoke test passed.~%"))
