(load "tractatus-core.lisp")
(load "tractatus-periphery.lisp")
(load "tractatus-worlds.lisp")
(load "tractatus-ring.lisp")
(load "tractatus-axes.lisp")
(load "tractatus-persistence.lisp")

(in-package #:cl)

(defun expect (condition message)
  (unless condition
    (error "Test failed: ~A" message)))

(let* ((world (tractatus-worlds::make-doc-welt "wikipu-ecosystem" "graphlang/persistence.md"))
       (rules (make-hash-table :test 'equal))
       (valid-rule
         (make-instance 'tractatus-core::logische-regel
                        :hash-id "r-has-color"
                        :struktur :has-color
                        :validador (lambda (objects welt)
                                     (and (= (length objects) 2)
                                          (tractatus-core::instance-of-p (first objects) 'vehicle welt)
                                          (tractatus-core::instance-of-p (second objects) 'color welt)))))
       (snapshot-root #P"./tmp-snapshots/"))
  (tractatus-core::register-begriff world 'entity)
  (tractatus-core::register-begriff world 'vehicle :subclase-de 'entity)
  (tractatus-core::register-begriff world 'color :subclase-de 'entity)
  (tractatus-core::register-gegenstand world "car-1" :instancia-de 'vehicle)
  (tractatus-core::register-gegenstand world "color-red" :instancia-de 'color)
  (tractatus-ring::register-sign-binding "auto" "car-1" world)
  (tractatus-ring::register-sign-binding "rojo" "color-red" world)
  (setf (gethash :has-color rules) valid-rule)
  (tractatus-ring::process-sldb-document '(:fields ("El auto es rojo")) world rules)
  (tractatus-axes::define-axis world :rol '(objeto color))
  (tractatus-axes::project-concept world "car-1" :rol 'objeto)
  (tractatus-axes::project-concept world "color-red" :rol 'color)
  (let* ((saved-path (tractatus-persistence::save-welt-snapshot world snapshot-root))
         (loaded-world (tractatus-persistence::load-welt-snapshot saved-path))
         (sv (make-instance 'tractatus-core::sachverhalt
                            :objekte '("car-1" "color-red")
                            :struktur :has-color)))
    (expect (tractatus-core::truth-of sv loaded-world)
            "loaded world should preserve asserted facts")
    (expect (string= (tractatus-axes::concept-axis-bitstring loaded-world "car-1" :rol)
                     "10")
            "loaded world should preserve axis projections")
    (expect (string= (tractatus-ring::resolve-name "auto" loaded-world)
                     "car-1")
            "loaded world should preserve sign bindings"))
  (format t "Persistence smoke test passed.~%"))
