(load "tractatus-core.lisp")
(load "tractatus-periphery.lisp")
(load "tractatus-worlds.lisp")
(load "tractatus-ring.lisp")

(in-package #:cl)

(defun expect (condition message)
  (unless condition
    (error "Test failed: ~A" message)))

(let* ((doc-world (tractatus-worlds::make-doc-welt "wikipu-ecosystem" "graphlang/spec.md"))
       (section-world (tractatus-worlds::make-section-welt "wikipu-ecosystem"
                                                           "graphlang/spec.md"
                                                           "Query Model"))
       (branch-world (tractatus-worlds::make-branch-welt "wikipu-ecosystem"
                                                          "feature/weltgraph-spec-core"))
       (repo-world (tractatus-worlds::make-repo-welt "wikipu-ecosystem"))
       (lang-world (tractatus-worlds::make-lang-welt "minimal-unl"))
       (lex-world (tractatus-worlds::make-lex-welt "wikipu-ecosystem" "seed-vocabulary")))
  (expect (string= (tractatus-core::hash-id doc-world)
                   "doc/wikipu-ecosystem/graphlang/spec-md")
          "doc world id should normalize paths")
  (expect (string= (tractatus-core::hash-id section-world)
                   "section/wikipu-ecosystem/graphlang/spec-md/query-model")
          "section world id should normalize section names")
  (expect (string= (tractatus-core::hash-id branch-world)
                   "branch/wikipu-ecosystem/feature-weltgraph-spec-core")
          "branch world id should flatten branch names")
  (expect (string= (tractatus-worlds::infer-parent-welt-id (tractatus-core::hash-id section-world))
                   "doc/wikipu-ecosystem/graphlang/spec-md")
          "section parent should point to doc world")
  (expect (string= (tractatus-worlds::infer-parent-welt-id (tractatus-core::hash-id branch-world))
                   "repo/wikipu-ecosystem")
          "branch parent should point to repo world")
  (expect (tractatus-worlds::direct-ingestion-allowed-p doc-world)
          "doc world should allow direct ingestion")
  (expect (tractatus-worlds::direct-ingestion-allowed-p repo-world)
          "repo world should allow direct ingestion as a local shared context")
  (expect (tractatus-worlds::direct-ingestion-allowed-p lang-world)
          "language worlds should allow direct ingestion")
  (expect (tractatus-worlds::direct-ingestion-allowed-p lex-world)
          "lexical worlds should allow direct ingestion")
  (format t "World smoke test passed.~%"))
