(:WELT-ID "lex/wikipu-ecosystem/cocina" :DIMENSIONS
 ((:ID :PARTE-COMESTIBLE :QUESTION NIL :TYPE :CATEGORICAL-ONE-HOT :VALUES
   (HOJA RAIZ TALLO))
  (:ID :ESTRUCTURA-HOJA :QUESTION NIL :TYPE :CATEGORICAL-ONE-HOT :VALUES
   (CABEZA-COMPACTA HOJA-SUELTA)))
 :CONTEXTS
 ((:ID :K-COCINA-VERDURAS :UNIVERSE (LECHUGA ZANAHORIA ESPINACA) :TASK
   :DIFERENCIAR :TREE
   (:DIMENSION :PARTE-COMESTIBLE :BRANCHES
    ((HOJA :NEXT
      (:DIMENSION :ESTRUCTURA-HOJA :BRANCHES
       ((CABEZA-COMPACTA) (HOJA-SUELTA))))
     (RAIZ) (TALLO)))))
 :PROJECTIONS
 ((:CONTEXT :K-COCINA-VERDURAS :CONCEPTS
   ((:CONCEPT LECHUGA :VALUES
     ((:PARTE-COMESTIBLE HOJA) (:ESTRUCTURA-HOJA CABEZA-COMPACTA)))
    (:CONCEPT ZANAHORIA :VALUES ((:PARTE-COMESTIBLE RAIZ)))
    (:CONCEPT ESPINACA :VALUES
     ((:PARTE-COMESTIBLE HOJA) (:ESTRUCTURA-HOJA HOJA-SUELTA)))))))
