;;; test-discrimination.lisp
;;; Tests for higher-functions/tractatus-discrimination
;;; Depends on: tractatus-signatures, tractatus-discrimination

(defpackage :test-discrimination
  (:use :cl :tractatus-signatures :tractatus-discrimination)
  (:export #:run-discrimination-tests))

(in-package :test-discrimination)

(defun test-m0-matrix-creation ()
  (format t "Test: M0 (Concept × Feature) matrix creation... ")
  (let* ((concepts '(:car :bike :tree))
         (features '(:color :size :shape))
         (concept-features '((:car (:color :red :size :small :shape :sedan)
                              :bike (:color :blue :size :medium :shape :mountain)
                              :tree (:color :green :size :large :shape :oak))))
         (m0 (make-m0 concepts features concept-features)))
    (assert (matrix-p m0))
    (assert (equal (matrix-rows m0) concepts))
    (assert (equal (matrix-cols m0) features))
    (format t "PASSED~%")))

(defun test-m1-matrix-transpose ()
  (format t "Test: M1 matrix transpose... ")
  (let* ((concepts '(:car :bike))
         (features '(:color :size))
         (concept-features '((:car (:color :red :size :small)
                              :bike (:color :blue :size :medium))))
         (m1 (make-m1 concepts features concept-features))
         (m1t (m1-transpose m1)))
    (assert (matrix-p m1t))
    (assert (equal (matrix-rows m1t) features))
    (assert (equal (matrix-cols m1t) concepts))
    (format t "PASSED~%")))

(defun test-bucket-detection ()
  (format t "Test: Bucket detection for feature values... ")
  (let* ((concepts '(:car :bike :tree))
         (features '(:color))
         (concept-features '((:car (:color :red)
                              :bike (:color :blue)
                              :tree (:color :green))))
         (m0 (make-m0 concepts features concept-features))
         (buckets (buckets m0 :color)))
    (assert (assoc :red buckets))
    (assert (assoc :blue buckets))
    (assert (assoc :green buckets))
    (format t "PASSED~%")))

(defun test-collision-detection ()
  (format t "Test: Collision detection in buckets... ")
  (let* ((concepts '(:car1 :car2 :bike))
         (features '(:color))
         (concept-features '((:car1 (:color :red)
                              :car2 (:color :red)
                              :bike (:color :blue))))
         (m0 (make-m0 concepts features concept-features))
         (collisions (detect-collisions m0 :color)))
    (assert (assoc :red collisions))
    (format t "PASSED~%")))

(defun run-discrimination-tests ()
  (format t "~%=== Running Discrimination Tests ===~%")
  (test-m0-matrix-creation)
  (test-m1-matrix-transpose)
  (test-bucket-detection)
  (test-collision-detection)
  (format t "=== All Discrimination Tests Passed ===~%~%"))
